### ISSUE TITLE
Ticking entity - Crash my server (1.18.2)

### ISSUE THREAD

**Issue by Davokushi** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#14] opened 2022-07-07 15:46 UTC
Crash my server when i spawn some mob of the mod... (i konw i have tooooo much mods but i like playing with minecraft mods jajaj)

Minecraft version: 1.18.2
Forge version: 40.1.52/1.18.2
Mod version: CNB-1.18.2-1.3.1

[crash-2022-07-07_10.33.09-server.txt](https://github.com/Joo5h/Creatures_And_Beasts-Forge/files/9065368/crash-2022-07-07_10.33.09-server.txt)

**Comment by Dariensg** [comment] 2022-07-07 23:57
This looks like it's most likely being caused by another mod. It's hard to tell which given the number. Could you test with just Creatures and Beasts to make sure the crash doesn't persist?

**Comment by Davokushi** [comment] 2022-07-08 02:38
you're right it's another mod, I used Geckolib and CNB and it didn't crash anymore... btw the mob that crashed was just "Cactman" I think I'll try 1 by 1 to see which mod makes it crash... I don't know if you want me to close it post or I inform you what mod causes that crash...

![2022-07-07_21 31 51](https://user-images.githubusercontent.com/108887945/177905711-4f12f5d7-c054-4689-85c0-464e3d5fa0ee.png)

**Comment by Davokushi** [comment] 2022-07-08 02:39
This looks like it's most likely being caused by another mod. It's hard to tell which given the number. Could you test with just Creatures and Beasts to make sure the crash doesn't persist?

![2022-07-07_21 31 51](https://user-images.githubusercontent.com/108887945/177905980-eb09dff4-b73e-465b-ba32-65f8ed0adc38.png)

**Comment by Davokushi** [comment] 2022-07-08 02:42
You're right, it's another mod, I tried only with Geckolib and CNB and it no longer crashed btw the mob that crashed was the "Cactman" I don't know if you want me to close the post or tell you which mod is the one that creashea I'm going to try 1 by 1






![2022-07-07_21 31 51](https://user-images.githubusercontent.com/108887945/177906253-1d669e39-f636-4545-ab3e-1d6a84800dbc.png)

**Comment by Dariensg** [comment] 2022-07-08 12:54
Closing this issue as it is not Creatures and Beasts.

**Closed as completed by Dariensg** 2022-07-08 12:54 UTC
Labels: bug, 1.18
