### ISSUE TITLE
1.18.2 server crash on startup

### ISSUE THREAD

**Issue by Valecrow** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#17] opened 2022-07-12 12:28 UTC
[crash-2022-07-12_14.23.24-fml.txt](https://github.com/Joo5h/Creatures_And_Beasts-Forge/files/9092768/crash-2022-07-12_14.23.24-fml.txt)

Not sure what's going on with it, but whenever I try and start my multiplayer server with CNB installed, it just refuses to start at all - tried multiple times and made sure I was using the most up to date version of GeckoLib for 1.18.2

**Comment by Dariensg** [comment] 2022-07-12 12:38
Your Creatures and Beasts version is outdated. The issue was fixed in 1.3.1, but you should update to the latest 1.18.2 version (1.3.2) to ensure having all fixes. Closing the issue as the problem is already resolved in more recent versions.

**Closed as completed by Dariensg** 2022-07-12 12:38 UTC
Labels: bug, duplicate, 1.18
