### ISSUE TITLE
Crashes when loading the game

### ISSUE THREAD

**Issue by ambr0sial** [CGessinger/Creatures-And-Beasts-Minecraft-Mod#26] opened 2022-08-04 18:39 UTC
Hello! So basically when trying to launch the game a crash log is created.

Game Version: 1.19
Forge Version: 41.1.0
CNB Version: 1.3.3

[crash-2022-08-04_20.31.19-fml.txt](https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/files/9262367/crash-2022-08-04_20.31.19-fml.txt)

Thank you in advance!

**Comment by Dariensg** [comment] 2022-08-04 18:48
Duplicate of #24. There is a beta in the Discord that should work on that version if you're interested, but it should be released within a week. Closing as it is a duplicate issue.

**Closed as completed by Dariensg** 2022-08-04 18:48 UTC
Labels: duplicate, 1.19
